[programs.devnet]
atlas_vesting = "J5bepnaUiZ5RR3NRKquGrePAMp9zbm9mHWqx7mvVdezy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./test-keypair.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
